/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

# ------------------------------------------------------------
# SCHEMA DUMP FOR TABLE: players
# ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS `players` (
  `name` varchar(50) NOT NULL,
  `team_acronym` varchar(20) DEFAULT NULL,
  `team_name` varchar(50) DEFAULT NULL,
  `games_played` int DEFAULT NULL,
  `minutes_per_game` varchar(10) DEFAULT NULL,
  `field_goals_attempted_per_game` decimal(3, 1) DEFAULT NULL,
  `field_goals_made_per_game` decimal(3, 1) DEFAULT NULL,
  `field_goal_percentage` decimal(4, 1) DEFAULT NULL,
  `free_throw_percentage` decimal(4, 1) DEFAULT NULL,
  `three_point_attempted_per_game` decimal(3, 1) DEFAULT NULL,
  `three_point_made_per_game` decimal(3, 1) DEFAULT NULL,
  `three_point_percentage` decimal(4, 1) DEFAULT NULL,
  `points_per_game` decimal(3, 1) DEFAULT NULL,
  `offensive_rebounds_per_game` decimal(3, 1) DEFAULT NULL,
  `defensive_rebounds_per_game` decimal(3, 1) DEFAULT NULL,
  `rebounds_per_game` decimal(3, 1) DEFAULT NULL,
  `assists_per_game` decimal(3, 1) DEFAULT NULL,
  `steals_per_game` decimal(3, 1) DEFAULT NULL,
  `blocks_per_game` decimal(3, 1) DEFAULT NULL,
  `turnovers_per_game` decimal(3, 1) DEFAULT NULL,
  `player_efficiency_rating` decimal(2, 1) DEFAULT NULL,
  PRIMARY KEY (`name`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

# ------------------------------------------------------------
# DATA DUMP FOR TABLE: players
# ------------------------------------------------------------

INSERT INTO
  `players` (
    `name`,
    `team_acronym`,
    `team_name`,
    `games_played`,
    `minutes_per_game`,
    `field_goals_attempted_per_game`,
    `field_goals_made_per_game`,
    `field_goal_percentage`,
    `free_throw_percentage`,
    `three_point_attempted_per_game`,
    `three_point_made_per_game`,
    `three_point_percentage`,
    `points_per_game`,
    `offensive_rebounds_per_game`,
    `defensive_rebounds_per_game`,
    `rebounds_per_game`,
    `assists_per_game`,
    `steals_per_game`,
    `blocks_per_game`,
    `turnovers_per_game`,
    `player_efficiency_rating`
  )
VALUES
  (
    'Aaron Brooks',
    'min',
    'Minnesota Timberwolves',
    23,
    '6:38',
    2.2,
    1.0,
    43.1,
    75.0,
    0.9,
    0.3,
    33.3,
    2.3,
    0.2,
    0.3,
    0.6,
    0.7,
    0.2,
    0.0,
    0.3,
    0.8
  );
INSERT INTO
  `players` (
    `name`,
    `team_acronym`,
    `team_name`,
    `games_played`,
    `minutes_per_game`,
    `field_goals_attempted_per_game`,
    `field_goals_made_per_game`,
    `field_goal_percentage`,
    `free_throw_percentage`,
    `three_point_attempted_per_game`,
    `three_point_made_per_game`,
    `three_point_percentage`,
    `points_per_game`,
    `offensive_rebounds_per_game`,
    `defensive_rebounds_per_game`,
    `rebounds_per_game`,
    `assists_per_game`,
    `steals_per_game`,
    `blocks_per_game`,
    `turnovers_per_game`,
    `player_efficiency_rating`
  )
VALUES
  (
    'Aaron Gordon',
    'orl',
    'Orlando Magic',
    38,
    '33:49',
    14.8,
    6.6,
    44.7,
    73.5,
    5.8,
    2.1,
    35.1,
    18.3,
    1.6,
    6.6,
    8.3,
    2.1,
    0.9,
    0.7,
    1.9,
    2.0
  );
INSERT INTO
  `players` (
    `name`,
    `team_acronym`,
    `team_name`,
    `games_played`,
    `minutes_per_game`,
    `field_goals_attempted_per_game`,
    `field_goals_made_per_game`,
    `field_goal_percentage`,
    `free_throw_percentage`,
    `three_point_attempted_per_game`,
    `three_point_made_per_game`,
    `three_point_percentage`,
    `points_per_game`,
    `offensive_rebounds_per_game`,
    `defensive_rebounds_per_game`,
    `rebounds_per_game`,
    `assists_per_game`,
    `steals_per_game`,
    `blocks_per_game`,
    `turnovers_per_game`,
    `player_efficiency_rating`
  )
VALUES
  (
    'Abdel Nader',
    'bos',
    'Boston Celtics',
    22,
    '7:26',
    2.1,
    0.7,
    34.8,
    33.3,
    1.1,
    0.4,
    33.3,
    1.9,
    0.2,
    0.7,
    1.0,
    0.3,
    0.2,
    0.2,
    0.4,
    0.6
  );
INSERT INTO
  `players` (
    `name`,
    `team_acronym`,
    `team_name`,
    `games_played`,
    `minutes_per_game`,
    `field_goals_attempted_per_game`,
    `field_goals_made_per_game`,
    `field_goal_percentage`,
    `free_throw_percentage`,
    `three_point_attempted_per_game`,
    `three_point_made_per_game`,
    `three_point_percentage`,
    `points_per_game`,
    `offensive_rebounds_per_game`,
    `defensive_rebounds_per_game`,
    `rebounds_per_game`,
    `assists_per_game`,
    `steals_per_game`,
    `blocks_per_game`,
    `turnovers_per_game`,
    `player_efficiency_rating`
  )
VALUES
  (
    'Adreian Payne',
    'orl',
    'Orlando Magic',
    5,
    '8:30',
    2.0,
    1.4,
    70.0,
    83.3,
    0.6,
    0.4,
    66.7,
    4.2,
    0.4,
    1.4,
    1.8,
    0.0,
    0.4,
    0.0,
    0.4,
    1.2
  );
INSERT INTO
  `players` (
    `name`,
    `team_acronym`,
    `team_name`,
    `games_played`,
    `minutes_per_game`,
    `field_goals_attempted_per_game`,
    `field_goals_made_per_game`,
    `field_goal_percentage`,
    `free_throw_percentage`,
    `three_point_attempted_per_game`,
    `three_point_made_per_game`,
    `three_point_percentage`,
    `points_per_game`,
    `offensive_rebounds_per_game`,
    `defensive_rebounds_per_game`,
    `rebounds_per_game`,
    `assists_per_game`,
    `steals_per_game`,
    `blocks_per_game`,
    `turnovers_per_game`,
    `player_efficiency_rating`
  )
VALUES
  (
    'Al Horford',
    'bos',
    'Boston Celtics',
    44,
    '32:39',
    10.5,
    5.4,
    51.3,
    72.5,
    3.3,
    1.5,
    43.5,
    13.3,
    1.5,
    6.3,
    7.8,
    5.3,
    0.6,
    1.1,
    1.9,
    1.9
  );
INSERT INTO
  `players` (
    `name`,
    `team_acronym`,
    `team_name`,
    `games_played`,
    `minutes_per_game`,
    `field_goals_attempted_per_game`,
    `field_goals_made_per_game`,
    `field_goal_percentage`,
    `free_throw_percentage`,
    `three_point_attempted_per_game`,
    `three_point_made_per_game`,
    `three_point_percentage`,
    `points_per_game`,
    `offensive_rebounds_per_game`,
    `defensive_rebounds_per_game`,
    `rebounds_per_game`,
    `assists_per_game`,
    `steals_per_game`,
    `blocks_per_game`,
    `turnovers_per_game`,
    `player_efficiency_rating`
  )
VALUES
  (
    'Al Jefferson',
    'ind',
    'Indiana Pacers',
    21,
    '14:24',
    5.9,
    3.1,
    52.8,
    80.0,
    0.0,
    0.0,
    0.0,
    7.0,
    0.9,
    3.7,
    4.5,
    0.9,
    0.4,
    0.5,
    0.7,
    2.0
  );
INSERT INTO
  `players` (
    `name`,
    `team_acronym`,
    `team_name`,
    `games_played`,
    `minutes_per_game`,
    `field_goals_attempted_per_game`,
    `field_goals_made_per_game`,
    `field_goal_percentage`,
    `free_throw_percentage`,
    `three_point_attempted_per_game`,
    `three_point_made_per_game`,
    `three_point_percentage`,
    `points_per_game`,
    `offensive_rebounds_per_game`,
    `defensive_rebounds_per_game`,
    `rebounds_per_game`,
    `assists_per_game`,
    `steals_per_game`,
    `blocks_per_game`,
    `turnovers_per_game`,
    `player_efficiency_rating`
  )
VALUES
  (
    'Al-Farouq Aminu',
    'por',
    'Portland Trail Blazers',
    35,
    '30:10',
    8.7,
    3.6,
    41.5,
    73.0,
    5.0,
    2.0,
    39.4,
    10.0,
    1.2,
    5.6,
    6.8,
    1.1,
    0.9,
    0.7,
    1.0,
    2.0
  );
INSERT INTO
  `players` (
    `name`,
    `team_acronym`,
    `team_name`,
    `games_played`,
    `minutes_per_game`,
    `field_goals_attempted_per_game`,
    `field_goals_made_per_game`,
    `field_goal_percentage`,
    `free_throw_percentage`,
    `three_point_attempted_per_game`,
    `three_point_made_per_game`,
    `three_point_percentage`,
    `points_per_game`,
    `offensive_rebounds_per_game`,
    `defensive_rebounds_per_game`,
    `rebounds_per_game`,
    `assists_per_game`,
    `steals_per_game`,
    `blocks_per_game`,
    `turnovers_per_game`,
    `player_efficiency_rating`
  )
VALUES
  (
    'Alec Burks',
    'uth',
    'Utah Jazz',
    44,
    '18:18',
    7.6,
    3.2,
    41.7,
    86.8,
    2.5,
    0.8,
    33.6,
    9.5,
    0.4,
    2.9,
    3.3,
    1.1,
    0.8,
    0.2,
    1.0,
    1.3
  );
INSERT INTO
  `players` (
    `name`,
    `team_acronym`,
    `team_name`,
    `games_played`,
    `minutes_per_game`,
    `field_goals_attempted_per_game`,
    `field_goals_made_per_game`,
    `field_goal_percentage`,
    `free_throw_percentage`,
    `three_point_attempted_per_game`,
    `three_point_made_per_game`,
    `three_point_percentage`,
    `points_per_game`,
    `offensive_rebounds_per_game`,
    `defensive_rebounds_per_game`,
    `rebounds_per_game`,
    `assists_per_game`,
    `steals_per_game`,
    `blocks_per_game`,
    `turnovers_per_game`,
    `player_efficiency_rating`
  )
VALUES
  (
    'Alec Peters',
    'pho',
    'Phoenix Suns',
    5,
    '11:30',
    2.6,
    0.8,
    30.8,
    100.0,
    2.4,
    0.6,
    25.0,
    2.8,
    0.2,
    1.6,
    1.8,
    1.0,
    0.0,
    0.4,
    0.2,
    0.2
  );
INSERT INTO
  `players` (
    `name`,
    `team_acronym`,
    `team_name`,
    `games_played`,
    `minutes_per_game`,
    `field_goals_attempted_per_game`,
    `field_goals_made_per_game`,
    `field_goal_percentage`,
    `free_throw_percentage`,
    `three_point_attempted_per_game`,
    `three_point_made_per_game`,
    `three_point_percentage`,
    `points_per_game`,
    `offensive_rebounds_per_game`,
    `defensive_rebounds_per_game`,
    `rebounds_per_game`,
    `assists_per_game`,
    `steals_per_game`,
    `blocks_per_game`,
    `turnovers_per_game`,
    `player_efficiency_rating`
  )
VALUES
  (
    'Alex Abrines',
    'okc',
    'Oklahoma City Thunder',
    42,
    '14:55',
    3.7,
    1.4,
    39.0,
    85.7,
    2.5,
    1.0,
    38.3,
    4.4,
    0.4,
    1.2,
    1.6,
    0.4,
    0.5,
    0.0,
    0.5,
    1.6
  );
INSERT INTO
  `players` (
    `name`,
    `team_acronym`,
    `team_name`,
    `games_played`,
    `minutes_per_game`,
    `field_goals_attempted_per_game`,
    `field_goals_made_per_game`,
    `field_goal_percentage`,
    `free_throw_percentage`,
    `three_point_attempted_per_game`,
    `three_point_made_per_game`,
    `three_point_percentage`,
    `points_per_game`,
    `offensive_rebounds_per_game`,
    `defensive_rebounds_per_game`,
    `rebounds_per_game`,
    `assists_per_game`,
    `steals_per_game`,
    `blocks_per_game`,
    `turnovers_per_game`,
    `player_efficiency_rating`
  )
VALUES
  (
    'Alex Caruso',
    'lal',
    'Los Angeles Lakers',
    16,
    '12:43',
    2.3,
    1.0,
    43.2,
    20.0,
    0.7,
    0.3,
    36.4,
    2.3,
    0.3,
    0.8,
    1.1,
    1.6,
    0.4,
    0.1,
    0.6,
    1.2
  );
INSERT INTO
  `players` (
    `name`,
    `team_acronym`,
    `team_name`,
    `games_played`,
    `minutes_per_game`,
    `field_goals_attempted_per_game`,
    `field_goals_made_per_game`,
    `field_goal_percentage`,
    `free_throw_percentage`,
    `three_point_attempted_per_game`,
    `three_point_made_per_game`,
    `three_point_percentage`,
    `points_per_game`,
    `offensive_rebounds_per_game`,
    `defensive_rebounds_per_game`,
    `rebounds_per_game`,
    `assists_per_game`,
    `steals_per_game`,
    `blocks_per_game`,
    `turnovers_per_game`,
    `player_efficiency_rating`
  )
VALUES
  (
    'Alex Len',
    'pho',
    'Phoenix Suns',
    42,
    '20:45',
    5.5,
    3.0,
    55.5,
    73.7,
    0.0,
    0.0,
    0.0,
    8.4,
    2.7,
    5.4,
    8.1,
    1.3,
    0.3,
    0.9,
    1.3,
    2.2
  );

/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
