const mapInternalNameToOuternal = {
  name: "Name",
  team_acronym: "Team",
  team_name: "TeamName",
  games_played: "Games",
  minutes_per_game: "MPG",
  field_goals_attempted_per_game: "FGA",
  field_goals_made_per_game: "FGM",
  field_goal_percentage: "FG%",
  free_throw_percentage: "FT%",
  three_point_attempted_per_game: "3PA",
  three_point_made_per_game: "3PM",
  three_point_percentage: "3PT%",
  points_per_game: "Points",
  offensive_rebounds_per_game: "Orebounds",
  defensive_rebounds_per_game: "DRebounds",
  rebounds_per_game: "Rebounds",
  assists_per_game: "Assists",
  steals_per_game: "Steals",
  blocks_per_game: "Blocks",
  turnovers_per_game: "Turnovers",
  player_efficiency_rating: "Efficiency",
  id: "ID",
};
export default mapInternalNameToOuternal;
